version: "3.7"

networks:
  wasabi-guacamole:

volumes:

  postgres-data:
    driver: local
  guacamole-data:
    driver: local
  home:
    driver: local
  tor:
    driver: local

services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      #PGDATA: /var/lib/postgresql/data
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
      #POSTGRES_INITDB_ARGS: "--data-checksums"
      #POSTGRES_INITDB_XLOGDIR: ...
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - wasabi-guacamole

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    hostname: adminer
    ports:
      - 18080:8080
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - wasabi-guacamole

  guacd:
    image: ianblenke/docker-wasabi-guacamole_guacd
    restart: always
    container_name: guacd
    hostname: guacd
    ports:
      - 4822:4822
    environment:
      TORSOCKS: "torsocks -a tor -P 9050"
    restart: always
    networks:
      - wasabi-guacamole

  guacamole:
    image: ianblenke/docker-wasabi-guacamole_guacamole
    restart: always
    container_name: guacamole
    hostname: guacamole
    volumes:
      - guacamole-data:/data
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    ports:
      - 28080:8080
    restart: always
    networks:
      - wasabi-guacamole

  tor:
    hostname: tor
    container_name: tor
    image: ianblenke/docker-wasabi-guacamole_tor:latest
    volumes:
      - tor:/var/lib/tor
    restart: always
    networks:
      - wasabi-guacamole

  wasabi:
    container_name: wasabi
    hostname: wasabi
    image: ianblenke/wasabiwallet
    privileged: true
    ports:
    - "3389:3389"
    volumes:
    - "home:/home"
    environment:
      RDP_USERNAME: ${RDP_USERNAME}
      RDP_PASSWORD: ${RDP_PASSWORD}
    restart: always
    networks:
      - wasabi-guacamole

